name: Daily Database Update

on:
  schedule:
    # Runs daily at 5:00 AM UTC by default.
    # Use https://crontab.guru to customize the schedule.
    # Note: GitHub Actions schedules run on UTC time and may have slight delays.
    # Example: '0 9 * * *' would be 9:00 AM UTC (approx 4 or 5 AM EST depending on DST)
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI for testing

jobs:
  trigger_update:
    # Use the latest available Ubuntu runner
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Database Update on Railway
        env:
          # These values are read from GitHub Repository Secrets (see below)
          APP_URL: ${{ secrets.RAILWAY_APP_URL }}
          UPDATE_SECRET: ${{ secrets.UPDATE_SECRET_KEY }}
        run: |
          echo "Triggering update for $APP_URL"
          # Send POST request with the secret header
          # -f : Fail fast with exit code on server errors (like 403, 500)
          # -S : Show error message, but remain silent on success
          # -X POST : Specify the POST method
          # -H "Header: Value" : Add necessary headers
          # -H "Content-Length: 0" : Required for POST requests with no body
          curl -f -S -X POST "$APP_URL/trigger-update" \
               -H "X-Update-Secret: $UPDATE_SECRET" \
               -H "Content-Length: 0"

          echo "Trigger request completed with exit code $?."
